blank_issues_enabled: false

contact_links:
  - name: ❔ FAQ
    url: https://mmocr.readthedocs.io/en/dev-1.x/get_started/faq.html
    about: Is your question frequently asked?
  - name: 💬 Forum
    url: https://github.com/open-mmlab/mmocr/discussions
    about: Ask general usage questions and discuss with other MMOCR community members
  - name: 🌐 Explore OpenMMLab
    url: https://openmmlab.com/
    about: Get know more about OpenMMLab
